/* InkVerse seed data — runs once when db.json doesn't exist yet. */
const crypto = require('crypto');
const uid = () => crypto.randomBytes(8).toString('hex');
const hashPw = (pw, salt) => crypto.scryptSync(String(pw), salt, 64).toString('hex');
const stripTags = (html) => String(html || '').replace(/<[^>]*>/g, ' ');
const wordCount = (html) => stripTags(html).split(/\s+/).filter(Boolean).length;
const daysAgo = (n, h = 0) => new Date(Date.now() - n * 864e5 - h * 36e5).toISOString();

function build() {
  const mkUser = (name, email, role, verified, bio, color, joined) => {
    const salt = crypto.randomBytes(8).toString('hex');
    return { id: uid(), name, email, salt, passHash: hashPw('demo123', salt), role, verified, bio, banned: false, joinedAt: joined, avatarColor: color };
  };

  const admin = mkUser('InkVerse Admin', 'admin@demo.app', 'admin', true, 'Keeping InkVerse safe, one story at a time.', '#64748b', daysAgo(400));
  const ava = mkUser('Ava Sterling', 'ava@inkverse.app', 'writer', true, 'I write about love, loss, and the cities in between. Author of Embers of the Heart.', '#ec4899', daysAgo(380));
  const tunde = mkUser('Tunde Okafor', 'tunde@inkverse.app', 'writer', true, 'Thrillers, heists, and hard choices. Ex-journalist chasing adrenaline on the page.', '#f97316', daysAgo(350));
  const lena = mkUser('Lena Marsh', 'lena@inkverse.app', 'writer', false, 'Mystery writer. I believe every lighthouse keeps a secret.', '#06b6d4', daysAgo(290));
  const kofi = mkUser('Kofi Mensah', 'kofi@inkverse.app', 'writer', false, 'Collector of old myths and older lies.', '#22c55e', daysAgo(320));
  const rhea = mkUser('Rhea Solberg', 'rhea@inkverse.app', 'writer', false, 'Epic fantasy, one storm at a time.', '#3b82f6', daysAgo(300));
  const naoki = mkUser('Ito Naoki', 'naoki@inkverse.app', 'writer', true, 'Neon futures and quiet machines.', '#8b5cf6', daysAgo(310));
  const priya = mkUser('Priya Raman', 'priya@inkverse.app', 'writer', false, 'Comedy, chaos, and the occasional dragon.', '#f59e0b', daysAgo(260));
  const zainab = mkUser('Zainab Bello', 'writer@demo.app', 'writer', true, 'Storyteller from the desert road. Currently writing Sands of the Starless Road.', '#e11d48', daysAgo(280));
  const maya = mkUser('Maya Okon', 'reader@demo.app', 'reader', false, 'Just here for the stories.', '#14b8a6', daysAgo(120));
  const sam = mkUser('Sam Ede', 'sam@inkverse.app', 'reader', false, 'Weekend reader, professional procrastinator.', '#a3e635', daysAgo(90));

  const users = [admin, ava, tunde, lena, kofi, rhea, naoki, priya, zainab, maya, sam];

  const genres = ['Romance', 'Mythical', 'Fantasy', 'Action', 'Adventure', 'Mystery', 'Thriller', 'Sci-Fi', 'Comedy', 'Drama', 'Horror', 'Historical']
    .map(name => ({ id: uid(), name }));

  const mkNovel = (author, title, description, genreNames, cover, views, featured, createdDaysAgo) => ({
    id: uid(), authorId: author.id, title, description,
    genres: genreNames, cover, status: 'published', featured, views, createdAt: daysAgo(createdDaysAgo)
  });

  const n1 = mkNovel(ava, 'Embers of the Heart', 'Ten years after the fire that took everything, Efe Adanna returns to Lagos to sell the family land — and runs into the one person she never planned to see again. Tobi Balogun was her childhood shadow, her first heartbreak, and the only witness to what really happened that night. Old wounds, new rain, and a city that never forgives: a story about loving someone through the ruins.', ['Romance', 'Drama'], '/covers/c1.jpg', 12840, true, 160);
  const n2 = mkNovel(ava, 'The Glass Orchard', "After her mother's death, Iva inherits the only thing her mother ever truly loved: an orchard of impossible trees that grow glass fruit in winter and whisper in voices the neighbors pretend not to hear. To sell it, Iva must understand it — and to understand it, she must forgive the woman who planted it.", ['Drama'], '/covers/c2.jpg', 3120, false, 90);
  const n3 = mkNovel(tunde, 'Last Bullet in Lagos', "Kash Danladi was the agency's best ghost until a job in Port Harcourt went loud and buried his team. Now a civilian with a bad knee and worse memories, Kash gets one last message from a dead colleague: a location, a time, and a single bullet with his name carved on it. To find out who sent it, Kash must come out of retirement — and back into the city that made him.", ['Action', 'Thriller'], '/covers/c3.jpg', 9870, false, 130);
  const n4 = mkNovel(lena, 'The Hollow Lighthouse', 'For forty years, the Harrow Point lighthouse has stood dark and empty — the keeper vanished, the logbook ends mid-sentence, and the lamp itself was found shattered from the inside. When disgraced journalist Wren Cassidy arrives to write a fluff piece about the restoration, she finds the tower is not empty at all. Someone has been living there. Someone who knows her name.', ['Mystery', 'Thriller'], '/covers/c4.jpg', 7430, false, 110);
  const n5 = mkNovel(kofi, 'The Jade Serpent Court', "Every hundred years, the Jade Serpent wakes beneath the old capital and calls its Court: nine houses, nine debts, one throne of rain. Efua Mansa, archivist and disgrace of the ninth house, is summoned in her dead grandmother's place — and discovers the Serpent does not want tribute this time. It wants a trial.", ['Mythical', 'Fantasy'], '/covers/c5.jpg', 11020, false, 200);
  const n6 = mkNovel(rhea, 'Crown of Storms', 'The Stormcrown has chosen a king every three hundred years, and it has never once chosen gently. This time it has fallen from the sky and landed at the feet of Solvei, a ferry pilot with debts, no surname, and no interest in thrones. Unfortunately for Solvei, the crown does not care about interest. It only cares about the one who caught it.', ['Fantasy', 'Adventure'], '/covers/c6.jpg', 15230, true, 220);
  const n7 = mkNovel(naoki, 'Neon Requiem', "In a city where memories can be bought, pawned, and stolen, courier Ren Osei carries a single encrypted memory chip across forty floors of hostile neon — a memory that belongs to the city's most wanted dead man. If Ren delivers it, the debt is cleared. If Ren looks at it, everyone dies. Ren, who has never once looked, is about to look.", ['Sci-Fi', 'Thriller'], '/covers/c7.jpg', 13600, true, 140);
  const n8 = mkNovel(priya, 'My Roommate Is a Dragon', 'Grad student Dev found a roommate the usual way: a desperate listing, an interview, a handshake. He did not read the fine print. Ignis pays rent on time, keeps odd hours, hoards the kitchenware, and is — as the lease technically disclosed — a 400-year-old dragon in human-ish shape. The rent is controlled. The chaos is not.', ['Comedy', 'Fantasy'], '/covers/c8.jpg', 8910, false, 75);
  const n9 = mkNovel(zainab, 'Sands of the Starless Road', "A thousand years ago, someone stole the stars from the desert sky and the caravans have been walking blind ever since. Amina, a navigator's daughter with a broken compass and a map that only shows places that no longer exist, joins the last great caravan of the season — carrying a letter to the thief himself.", ['Adventure', 'Fantasy'], '/covers/c9.jpg', 6540, false, 60);

  const novels = [n1, n2, n3, n4, n5, n6, n7, n8, n9];

  const chapters = [];
  let seq = 0;
  const ch = (novel, title, content, status, created, updated) => {
    seq++;
    chapters.push({ id: uid(), novelId: novel.id, title, content, status, order: chapters.filter(c => c.novelId === novel.id).length + 1, createdAt: daysAgo(created), updatedAt: daysAgo(updated, seq % 9), wordCount: wordCount(content) });
  };

  /* ---- Embers of the Heart ---- */
  ch(n1, 'The City We Left', `<p>The taxi crawled over the Third Mainland Bridge, and Efe pressed her forehead against the window like a child. Ten years. Ten years, and Lagos had not waited for her. The skyline had teeth now, glass towers biting into a sky the color of wet cement.</p><p>"Madam, you okay?" the driver asked, watching her in the mirror.</p><p>"I'm fine," she lied. She was not fine. Somewhere past the water, past the markets and the honking and the heat, there was a street in Surulere with a burnt-out house on it, and on that street waited the reason she had flown two thousand miles to sign a single paper.</p><p>Her phone buzzed. A message from her aunt: <em>The buyers are ready. Come and finish it.</em></p><p>Efe typed back nothing. Instead she watched the lagoon glitter below the bridge and tried to remember the last time she had stood on this road. She had been seventeen. Tobi had been beside her, holding her hand so hard her knuckles ached, and behind them, past the smoke, their whole childhood was burning.</p>`, 'published', 160, 12);
  ch(n1, 'Rain Over Maroko', `<p>It started to rain the moment she stepped out of the bank, as if the city had been waiting to corner her. Efe ducked under the awning of a closed boutique and shook the water from her sleeve, and that was when she heard it.</p><p>"Efe?"</p><p>The voice had grown up. The voice had edges now. But she would have known it anywhere, the way you know a song you swore you had forgotten.</p><p>Tobi Balogun stood two meters away, soaked to the skin, a folder of papers clutched against his chest. He looked at her the way people look at weather — like she had just rolled in off the sea.</p><p>"You're here," he said, finally.</p><p>"I'm here," she said.</p><p>The rain came down harder, drumming the awning, and neither of them moved. Ten years of silence stood between them, politely waiting its turn.</p>`, 'published', 130, 9);
  ch(n1, 'What the Fire Kept', `<p>The house was smaller than she remembered. Fires do that; they shrink the world down to a black frame and a memory of rooms.</p><p>Tobi walked the boundary with her, pointing out where the fence had been, where the mango tree stood. His shoulder brushed hers once, and neither of them apologized.</p><p>"You never wrote," he said.</p><p>"You never called."</p><p>"I didn't have the number, Efe. You left before anyone could—"</p><p>"I left because staying was burning me alive."</p><p>Silence again. A gecko clicked somewhere in the ruins. Then Tobi reached into his bag and pulled out a tin box, rusted at the hinges, and Efe's breath stopped, because she recognized it. It was the box they had buried under the mango tree the summer they turned sixteen — the one with the letters, the photographs, the list of everything they swore they would never become.</p><p>"The fire didn't take everything," he said quietly. "I dug it out the next morning."</p>`, 'published', 95, 3);

  /* ---- The Glass Orchard ---- */
  ch(n2, 'The Inheritance', `<p>The lawyer pronounced the word <em>orchard</em> the way other people pronounce <em>debt</em>. Iva signed where the pen had made a small X and became, at twenty-nine, the owner of forty-one trees she had never once been allowed to touch.</p><p>"Your mother was specific," the lawyer said. "No cutting. No sale for five years. She wrote a letter too. She made me promise to give it to you only after the first frost."</p><p>That was in September. The first frost came in November, white and early, and Iva drove out to the orchard at dawn with the letter unopened on the seat beside her.</p><p>The trees were wrong. She saw it from the gate. Every branch carried fruit made of something that was not fruit — pale, translucent, catching the weak sun and throwing it back in pieces. Glass. The orchard was full of glass.</p><p>And somewhere in the middle of it, very softly, something was humming her mother's favorite song.</p>`, 'published', 90, 20);
  ch(n2, 'What the Trees Remember', `<p>She opened the letter under the oldest tree, where the glass fruit hung low enough to touch.</p><p><em>Iva,</em> it began. <em>By now you have seen what grows here, and you are angry, because you were always braver than me, and bravery hates a secret. So I will give you the only one I have left.</em></p><p><em>The year before you were born, I lost a child. Your father left the morning I came home without her. I planted this orchard the same week — one tree for every year I thought I would not survive. I never expected anything to grow.</em></p><p><em>But grief is a strange gardener, Iva. It composts everything. Even joy.</em></p><p>Above her, a fruit shifted in the wind and rang, faintly, like a struck cup. Then another. Then the whole orchard answered, a hundred glass bells in a wind that had come from nowhere, and Iva sat in the cold grass with her mother's handwriting shaking in her hand and understood, finally, what she had inherited.</p><p>Not trees. The truth, at last, in a form her mother could bear.</p>`, 'published', 80, 14);

  /* ---- Last Bullet in Lagos ---- */
  ch(n3, 'The Package', `<p>The bullet arrived on a Tuesday, in a brown envelope with no sender, nestled in cotton like a gift. Kash turned it under the kitchen light. Someone had carved three letters into the brass with a needle or a knife, patient as sin.</p><p>K. D. A.</p><p>His old name. His dead name.</p><p>Underneath it was a scrap of paper with coordinates and a time: Friday, 9 p.m. The coordinates belonged to a street in Port Harcourt he had sworn never to walk again.</p><p>He told himself he wouldn't go. He told himself that for two whole days, while the bullet sat on the table and caught the light, and on Wednesday the second envelope came. This one held a photograph: his old unit, eight deep, taken an hour before the job that killed six of them. On the back, in handwriting he recognized like a scar, someone had written:</p><p><em>We were not betrayed by luck. Come and see who paid.</em></p><p>Kash looked at the bullet. His knee ached, as if it had been listening. "One last walk," he told the empty room. Nobody believed him, including the room.</p>`, 'published', 130, 11);
  ch(n3, 'Night Crossing', `<p>Port Harcourt at night is a city that does its own accounting. Kash moved through the old streets with the lights off in his eyes, counting exits out of habit: alley, fence, drain, river.</p><p>The coordinates ended at a cold warehouse on the waterfront, the kind of place where cargo goes to be forgotten. He was early. Whoever wrote the note was earlier — a figure at the far end of the loading bay, face under a hood, hands where he could see them.</p><p>"You kept the bullet," the figure said. A woman's voice. Familiar in a way that raised every hair on his arm.</p><p>"You're dead," Kash said. "I carried your vest out of that house."</p><p>"Then you carried the wrong body." She stepped into the light, and Kash felt Friday arrive four days early. "We have six hours, Kash. Six hours to catch the man who sold us, and then everyone who knew about the job — every one of us still breathing — goes into the ground. I came to give you a choice before it starts."</p><p>"What choice?"</p><p>"Run," she said, "or reload."</p>`, 'published', 120, 6);

  /* ---- The Hollow Lighthouse ---- */
  ch(n4, 'The Assignment', `<p>"It's a soft piece," the editor said, in the tone people use right before they hand you something rotten. "Lighthouse gets restored, town gets a ribbon-cutting, everyone smiles. Two thousand words."</p><p>Wren Cassidy took the assignment because she needed the work, and because she had stopped being afraid of anything after the libel case, which was its own kind of damage.</p><p>Harrow Point was three hours north, at the end of a road the GPS gave up on. The lighthouse stood on a fist of black rock joined to the mainland by a causeway that drowned at high tide. White tower, red door, no glass in the lamp room — just a dark socket open to the sky, like an eye with the pupil torn out.</p><p>The contractor met her at the door with his hat in his hands, which is never how contractors greet journalists.</p><p>"We can do the tour tomorrow," he said. "The crew won't go up today."</p><p>"Why not?"</p><p>He looked at the tower, then at the tide, then anywhere but at her. "Someone's been sleeping in the lamp room," he said. "And they wrote your name on the wall."</p>`, 'published', 110, 16);
  ch(n4, 'The Logbook', `<p>The town archive smelled of paper going slowly back to wood. Wren sat with the Harrow Point logbooks in a pool of desk-lamp light, photographing pages, and the last one was wrong in a way she couldn't immediately name.</p><p>The keeper's entries were neat for thirty-nine years. Weather, ships, oil. Then the final month: the handwriting loosens, the entries shorten, and the same sentence begins appearing between ordinary notes, like a cough between words. <em>The light is not for the ships.</em></p><p><em>October 3rd. Fog. The light is not for the ships. Cleaned the lens.</em></p><p><em>October 9th. Calm sea. The light is not for the ships. The light is not for the ships. Repaired the door latch.</em></p><p>The last entry was dated October 14th, and it ended mid-word, mid-syllable, the pen dragged off the page in a long black scar. Below it, in fresher ink — much fresher, Wren thought, close enough to smell — someone had finished the sentence.</p><p><em>It is a warning. Ask Wren Cassidy what it warns against.</em></p><p>The archive door clicked shut behind her. She had not heard it open.</p>`, 'published', 100, 5);

  /* ---- The Jade Serpent Court ---- */
  ch(n5, 'The Summons', `<p>The summons came as all such things did in the old capital: not by post, but by weather. Rain fell on Efua Mansa's doorstep alone, in a column, patiently, until she opened the door and held out her hand.</p><p>The rain gave her a scale. Green as bottle glass, heavy as a coin, warm as something alive.</p><p>"The Ninth House is called," said the rain, in her grandmother's voice, and stopped.</p><p>Efua stood a long time in the doorway. Her grandmother had been the Ninth House's seat at the Serpent's Court for sixty years, until the spring the river took her. Since then the house had consisted of Efua, an archive of forbidden ledgers, and a debt nobody would name.</p><p>"I'm not a seat," she told the wet step. "I'm a librarian."</p><p>The scale pulsed in her palm, once, like a second heart.</p><p><em>The Serpent does not call the worthy,</em> her grandmother had written, in the letter Efua had been forbidden to open and opened anyway. <em>It calls the owed. Go, little one. Bring my ledger. And whatever it asks — do not answer first.</em></p>`, 'published', 200, 25);
  ch(n5, 'The Court of Rain', `<p>The palace of the Jade Serpent exists the way a rumor exists: everyone in the old capital knows where it is, and no one can take you there. Efua found it the only way anyone ever had — by following the rain uphill.</p><p>The hall was open to the sky, and the sky was wrong with clouds. Eight seats ringed the water-clock floor: bone, bronze, driftwood, iron. The ninth seat was a place of bare stone, scrubbed pale, and every delegate watched her walk to it.</p><p>When the Serpent rose from the cistern at the center, it did not look at the tribute the other houses laid down — silk, salt, a cage of small bright birds. It looked at Efua, and its eyes were courtrooms.</p><p>"Ninth House," it said, and its voice was everyone she had ever lied to. "You come in place of the debtor Amma Mansa."</p><p>"I come," Efua said carefully, "in her place."</p><p>"Good. Then you inherit the question." The Serpent lowered its great head until she could see herself, small and crooked, in its eye. "Who stole my heart from this house, one hundred years ago?"</p><p>Somewhere behind her, eight delegates leaned forward at once.</p>`, 'published', 185, 18);

  /* ---- Crown of Storms ---- */
  ch(n6, 'The Falling', `<p>Solvei saw the storm coming an hour before it arrived, which was unusual, and saw the crown falling inside it, which was not supposed to be possible.</p><p>It came down slow, the way things fall in bad dreams — a ring of black iron, nine points, turning end over end through the green heart of the squall. Lightning did not strike the crown. Lightning kept out of its way.</p><p>"Do not," said her deckhand, Ymir, with great feeling. "Solvei. We are ferry folk. Whatever that is, it belongs to the sky."</p><p>It landed on the prow of the ferry, silent as snow, and the storm stopped. Not faded — stopped. The waves lay down. The rain hung in the air, every drop still, a curtain of glass beads.</p><p>In the silence, Solvei could hear her own heart making its idiot argument, and beneath it, smaller, patient, the crown making its.</p><p>She picked it up. Of course she picked it up. It was in her hand before she had decided anything, the way a rope comes to a sailor's hand in weather, and the whole frozen storm exhaled — and three hundred years of law woke up, stretched, and came looking for her.</p>`, 'published', 220, 13);
  ch(n6, 'The Nine Refusals', `<p>"There is a ceremony," said the envoy from the Stormcrown Temple, reading from a scroll older than Solvei's entire family, "in which the bearer of the crown must refuse it nine times before the sky accepts the refusal is real. Or before the bearer stops refusing. History is evenly divided."</p><p>"I refuse," said Solvei.</p><p>The envoy ticked a box. "One."</p><p>"I refuse because I have debts, a boat, and a bad knee."</p><p>"Two. Note that the knee will be healed. Three."</p><p>"I refuse because I don't know you, because I don't trust you, and because anything that falls out of the sky in a storm and lands at your feet is either a trap or a curse."</p><p>"Four, five, and six, respectfully," said the envoy. "Historically that speech has been given by almost every bearer."</p><p>Ymir, from the deck, raised a hand. "Question. What happens at nine?"</p><p>The envoy rolled the scroll shut and looked at Solvei with something that might have been pity. "At nine, the sky picks someone else, and the crown goes back up." He pointed, politely, at the ceiling, at the clouds, at the storm that had been following their ferry for two days now, patient as a dog. "It has never once gone back up."</p>`, 'published', 205, 2);

  /* ---- Neon Requiem ---- */
  ch(n7, 'The Chip', `<p>The dead man's memory weighed eleven grams, courier-sealed in a black case, and Ren Osei was carrying it through Kowloon Stack at two in the morning with every gang on levels twenty through forty bidding on his location.</p><p>"Do not look at it," the broker had said, handing it over. "Do not pawn it. Do not even think about it hard. Deliver it to the Lantern Hotel, room 4040, and the debt is cleared. Ren — your mother's debt, too."</p><p>That was the hook, and Ren had known it was the hook, and taken the case anyway.</p><p>Now, pressed into a stairwell alcove on level twenty-six while a drone sweep painted the corridor outside, Ren made the mistake of looking at the case in his hand. Small. Scratched. Eleven grams of someone's last morning.</p><p>Dead men's memories sell high because they cannot testify. This one had belonged to Ebi Vance: whistle-blower, traitor, saint, depending on which news feed you bought. He had died six days ago in the Lantern Hotel, in room 4040.</p><p>The room Ren was being paid to deliver the memory to.</p><p>The drone sweep passed. Ren stayed in the alcove, breathing quietly, doing arithmetic he did not want to finish.</p>`, 'published', 140, 8);
  ch(n7, 'Room 4040', `<p>The Lantern Hotel had forty floors and no lobby. You entered it the way you entered everything in the Stack: sideways, through someone else's permission.</p><p>Ren climbed. Lifts were for people who wanted to be recorded.</p><p>On thirty-three, he passed a chapel of recycled servers where monks were praying to something that might have been an AI or might have been a fire; on thirty-six, a market selling memories by the gram, and he crossed the street of it quickly, the case held tight against his ribs. Behind the stalls, a woman with mirror eyes watched him pass and spoke into her wrist.</p><p>Forty. The corridor to 4040 was clean, which is the most suspicious thing a corridor in the Stack can be.</p><p>The door was ajar.</p><p>Ren stood a long time in the corridor listening to nothing. Then, because the broker's voice in his head had gone quiet, and because eleven grams is not a weight you can carry forever, he did the thing he had never once done in six years of carrying.</p><p>He put the chip into his reader, and he looked.</p><p>The memory opened like a door in his skull. Somewhere in it, Ebi Vance was still alive, saying: <em>If you're watching this, courier, then the delivery already happened. The question is — did you deliver it to me, or to them?</em></p>`, 'published', 125, 1);

  /* ---- My Roommate Is a Dragon ---- */
  ch(n8, 'The Fine Print', `<p>In hindsight, the warning signs were load-bearing. The listing said: <em>Room available. Sunny. Must love warmth. No landlords. No knights. Rent negotiable if you can cook.</em></p><p>Dev, who had been apartment-hunting for two months in a market where closets listed themselves as studios, read it as "quirky." He shook the hand of the tall, copper-eyed woman in the scorched bathrobe, signed the lease, and moved in on a Saturday.</p><p>By Wednesday, he had noticed that the radiator never came on and the flat was tropical. By Friday, he had noticed the kitchen knives were missing. All of them. Not stolen — relocated, arranged on the highest shelf in neat gleaming rows, like trophies.</p><p>"Ignis," Dev said, carefully, over dinner. "Where are the knives?"</p><p>"Safe," said his roommate, tearing into a whole roasted chicken with the serene focus of someone who owned every bone in it. "You would dull them."</p><p>"I would <em>dull</em>—"</p><p>"Also," Ignis said, "the building inspector is coming tomorrow. If he asks, I am your cousin from the north."</p><p>"Which north?"</p><p>"Further north than he can imagine."</p>`, 'published', 75, 10);
  ch(n8, 'The Hoard', `<p>Every dragon has a hoard. Dev learned this on laundry day, when he opened the door of the spare room — officially "storage" — and came face to face with the economy.</p><p>There was gold, yes. But mostly there were: four hundred and eleven spoons (the knives were just the vanguard), nine hundred single socks that belonged to no machine in the building, a wall of library books, all of them overdue, a broken satellite dish, and what appeared to be the city's entire missing stock of left shoes.</p><p>"It's not about value," Ignis said from behind him, suddenly present the way cats are suddenly present. "It's about <em>rescue</em>. Everything in this room was lost, Dev. I found it."</p><p>"You found the satellite dish."</p><p>"It fell off a roof. It was crying."</p><p>"Dishes don't—"</p><p>"And before you ask," Ignis continued, steering him gently backward out of the room with one warm hand on his shoulder, "no, you may not have the spoons back. But I will tell you a secret worth more than spoons." Her copper eyes went slitted and old and merry. "The building inspector from Tuesday? He was the third one this year. The other two retired."</p>`, 'published', 68, 4);

  /* ---- Sands of the Starless Road ---- */
  ch(n9, 'The Last Caravan', `<p>The stars had been gone so long that children thought the dark above the dunes was the natural color of the sky, and that the old maps — the ones drawn in silver ink, with the constellations pinned along the margins like butterflies — were decoration.</p><p>Amina knew better. Her father had been a navigator back when the word still meant something, and he had left her two things when the sand took him: a compass that pointed somewhere other than north, and a map of places that no longer existed.</p><p>She stood at the edge of the gathering ground at first light, watching the last caravan of the season assemble — ninety camels, forty guards, one very old woman with a letter sealed in black wax.</p><p>"You're the navigator's daughter," the old woman said. It was not a question. "You carry his instruments and none of his fear. Good. I need both."</p><p>"Where does the letter go?" Amina asked.</p><p>The old woman looked up at the empty sky, the way other people look at graves. "To the man who took the stars," she said. "And before you refuse: the letter has your name on it. It has had your name on it for twenty years."</p>`, 'published', 60, 7);
  ch(n9, 'The Weight of Water', `<p>By the third day, the caravan had entered the kind of silence that has texture. No wind. No birds. Even the camels walked as if they were remembering something.</p><p>Amina rode point with the map on her knee, matching dunes to the places that no longer existed. Her father had taught her the trick of it: <em>The sand moves, but the thirst doesn't. Find where the wells were, and the old road finds you.</em></p><p>At the fourth well — dry, a mouth of cracked mud — they found the first sign of the other caravan. A fire pit, cold. A waterskin, full, left behind. Nobody in the desert leaves full water behind.</p><p>"We're not alone on the road," said the guard captain quietly.</p><p>The old woman said nothing. She sat down by the dead fire, took the black letter out of her robes, and held it in her lap like something that could hatch.</p><p>"Grandmother," Amina said. "Who is coming?"</p><p>"Everyone the stars owed a debt to," the old woman said. "Sit, child. It's time you learned what your father was before he was afraid. It's time you learned what I was before I was old." She turned the letter over. The seal, Amina saw now, was not wax at all — it was a small dark stone, and it was warm, and it was pulsing, faintly, like a heartbeat two thousand miles underground.</p><p>"We are carrying the thief's confession," the old woman said. "And confessions attract family."</p>`, 'published', 45, 2);
  ch(n9, 'The Map That Lies', `<p>On the seventh night, the map began to lie.</p><p>Amina noticed it the way navigators notice everything — sideways, through a wrongness too small to name. The old road on the page had bent a quarter inch east. A well that should have been dry was drawn with the silver line that meant <em>running water</em>. And in the margin, where the silver constellations used to be pinned like butterflies, one small star had reappeared.</p><p>She looked up. Nothing above but the seamless dark.</p><p>She looked down. One star, winking in the ink, exactly where the caravan would be standing at dawn.</p><p>"It's showing us where the road <em>will</em> be," she said slowly, "not where it was."</p><p>The old woman, who had come to stand beside her, made a sound like dry paper tearing. "Your father figured that out on his last crossing. It is why he stopped trusting the map. It is why he started trusting <em>himself</em> instead." A pause. "It is also, I think, why the road took him. The road does not like being predicted."</p><p>Far ahead, out where the dunes shouldered up against the dark, something glimmered once — low, gold, patient. The guard captain reached for his rifle. The old woman reached for his wrist.</p><p>"No," she said softly. "That is not a threat. That is a door."</p>`, 'published', 20, 0);
  ch(n9, 'The Thief\u2019s Door', `<p>Notes for next session: the caravan reaches the door at dawn. Who opens it from the other side? Idea — the thief is not a man. The letter was addressed to "the one who took the stars," and the taker was the sky itself, tired of being wished on.</p><p>Check the rhythm of the old woman's reveal. Maybe Amina's compass finally points at the door. End the chapter on the seal breaking.</p>`, 'draft', 2, 0);

  const bookmarks = [
    { userId: maya.id, novelId: n1.id, at: daysAgo(15) },
    { userId: maya.id, novelId: n4.id, at: daysAgo(9) },
    { userId: maya.id, novelId: n7.id, at: daysAgo(4) },
    { userId: sam.id, novelId: n6.id, at: daysAgo(11) }
  ];

  const h1 = db0(chapters, n1.id, 2); const h2 = db0(chapters, n7.id, 1); const h3 = db0(chapters, n9.id, 2);
  const history = [
    { userId: maya.id, novelId: n1.id, chapterId: h1, at: daysAgo(1) },
    { userId: maya.id, novelId: n7.id, chapterId: h2, at: daysAgo(3) },
    { userId: sam.id, novelId: n9.id, chapterId: h3, at: daysAgo(2) }
  ];

  const follows = [
    { followerId: maya.id, authorId: ava.id, at: daysAgo(30) },
    { followerId: maya.id, authorId: lena.id, at: daysAgo(12) },
    { followerId: maya.id, authorId: zainab.id, at: daysAgo(6) },
    { followerId: sam.id, authorId: rhea.id, at: daysAgo(20) },
    { followerId: sam.id, authorId: zainab.id, at: daysAgo(8) },
    { followerId: sam.id, authorId: ava.id, at: daysAgo(16) }
  ];

  const verifications = [
    { id: uid(), userId: lena.id, message: 'Published two novels and crossed 7,000 reads this season. Links to my press coverage are in my bio. Requesting the verified badge so readers know the account is genuine.', status: 'pending', at: daysAgo(5) }
  ];

  const reports = [
    { id: uid(), reporterId: sam.id, type: 'novel', targetId: n8.id, reason: 'Not sure this belongs under Comedy — feels more like children\u2019s content. Please review the genre tags.', status: 'open', at: daysAgo(2) }
  ];

  return { users, sessions: {}, genres, novels, chapters, bookmarks, history, follows, verifications, reports };

  function db0(chs, novelId, idx) {
    const list = chs.filter(c => c.novelId === novelId && c.status === 'published').sort((a, b) => a.order - b.order);
    return list[idx] ? list[idx].id : (list[0] ? list[0].id : null);
  }
}

module.exports = { build };
